services:
  frontend:
    build:
      context: ../XTJS-frontend
      dockerfile: Dockerfile.frontend
    image: project-xtjs-frontend:cec3-v3-20260924
    container_name: xtjs-frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network
