CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE xtjs_users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    identifier_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username        TEXT      NOT NULL,
    hashed_password TEXT      NOT NULL,
    role_level      SMALLINT  NOT NULL DEFAULT 1,
    display_name    TEXT,
    is_active       BOOLEAN   NOT NULL DEFAULT TRUE,
    failed_attempts SMALLINT  NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP,
    last_login_at   TIMESTAMP,
    deleted         BOOLEAN   NOT NULL DEFAULT FALSE,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_xtjs_users_role_level CHECK (role_level BETWEEN 1 AND 4)
);

COMMENT
ON TABLE xtjs_users IS 'XTJS用户表，承载登录账号与四级权限';

COMMENT
ON COLUMN xtjs_users.identifier_id IS '用户UUID唯一标识符，系统自动生成，作为主键';
COMMENT
ON COLUMN xtjs_users.id IS '数据库内部自增数字序号，仅用于内部排序/排查，不作为业务标识';
COMMENT
ON COLUMN xtjs_users.username IS '登录用户名，未删除范围内唯一';
COMMENT
ON COLUMN xtjs_users.hashed_password IS '密码的 bcrypt 哈希值，绝不存储明文';
COMMENT
ON COLUMN xtjs_users.role_level IS '权限等级：1-普通用户，2-中级用户，3-高级用户，4-管理员';
COMMENT
ON COLUMN xtjs_users.display_name IS '展示名称（可选）';
COMMENT
ON COLUMN xtjs_users.is_active IS '账号是否启用：false 表示已停用/封禁';
COMMENT
ON COLUMN xtjs_users.failed_attempts IS '连续登录失败次数，用于触发账号锁定';
COMMENT
ON COLUMN xtjs_users.locked_until IS '账号锁定到期时间，为空表示未锁定';
COMMENT
ON COLUMN xtjs_users.last_login_at IS '最近一次登录成功时间';
COMMENT
ON COLUMN xtjs_users.deleted IS '逻辑删除：false-未删除，true-已删除';
COMMENT
ON COLUMN xtjs_users.create_time IS '创建时间';
COMMENT
ON COLUMN xtjs_users.update_time IS '更新时间';

CREATE UNIQUE INDEX uk_xtjs_users_active_username
    ON xtjs_users (username)
    WHERE deleted = FALSE;

CREATE INDEX idx_xtjs_users_active_create_time
    ON xtjs_users (create_time DESC, identifier_id DESC)
    WHERE deleted = FALSE;
