CREATE TABLE xtjs_project_documents
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id               UUID      NOT NULL,
    tender_document_id       UUID      NOT NULL,
    business_bid_document_id UUID      NOT NULL,
    technical_bid_document_id UUID,
    create_time              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_project
        FOREIGN KEY (project_id)
            REFERENCES xtjs_projects (identifier_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_tender_document
        FOREIGN KEY (tender_document_id)
            REFERENCES xtjs_documents (identifier_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_business_bid_document
        FOREIGN KEY (business_bid_document_id)
            REFERENCES xtjs_documents (identifier_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_technical_bid_document
        FOREIGN KEY (technical_bid_document_id)
            REFERENCES xtjs_documents (identifier_id)
            ON DELETE CASCADE
);

COMMENT ON TABLE xtjs_project_documents IS 'XTJS项目文档关联表';
COMMENT ON COLUMN xtjs_project_documents.id IS '自增主键';
COMMENT ON COLUMN xtjs_project_documents.project_id IS '项目UUID，外键关联 xtjs_projects.identifier_id';
COMMENT ON COLUMN xtjs_project_documents.tender_document_id IS '招标文件UUID，外键关联 xtjs_documents.identifier_id';
COMMENT ON COLUMN xtjs_project_documents.business_bid_document_id IS '商务标文件UUID，外键关联 xtjs_documents.identifier_id';
COMMENT ON COLUMN xtjs_project_documents.technical_bid_document_id IS '技术标文件UUID，外键关联 xtjs_documents.identifier_id';
COMMENT ON COLUMN xtjs_project_documents.create_time IS '创建时间';

CREATE UNIQUE INDEX uk_project_documents_binding
    ON xtjs_project_documents (
        project_id,
        tender_document_id,
        business_bid_document_id,
        technical_bid_document_id
    )
    NULLS NOT DISTINCT;

CREATE INDEX idx_project_documents_tender
    ON xtjs_project_documents (tender_document_id);

CREATE INDEX idx_project_documents_business_bid
    ON xtjs_project_documents (business_bid_document_id);

CREATE INDEX idx_project_documents_technical_bid
    ON xtjs_project_documents (technical_bid_document_id);
