CREATE TABLE xtjs_tender_reviews
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    identifier_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_identifier_id UUID        NOT NULL UNIQUE REFERENCES xtjs_documents (identifier_id),
    status                 VARCHAR(16) NOT NULL DEFAULT 'running',
    overall_status         VARCHAR(16),
    passed_count           INTEGER     NOT NULL DEFAULT 0,
    failed_count           INTEGER     NOT NULL DEFAULT 0,
    unclear_count          INTEGER     NOT NULL DEFAULT 0,
    page_count             INTEGER     NOT NULL DEFAULT 0,
    text_length            INTEGER     NOT NULL DEFAULT 0,
    result_object_key      TEXT,
    error_message          TEXT,
    deleted                BOOLEAN     NOT NULL DEFAULT FALSE,
    create_time            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_xtjs_tender_reviews_status
        CHECK (status IN ('running', 'completed', 'failed')),
    CONSTRAINT chk_xtjs_tender_reviews_overall_status
        CHECK (overall_status IS NULL OR overall_status IN ('passed', 'failed', 'unclear'))
);

COMMENT ON TABLE xtjs_tender_reviews IS '独立招标文件审查记录，每份文档保留最新审查结果';
COMMENT ON COLUMN xtjs_tender_reviews.result_object_key IS '完整审查结果在 MinIO 中的 gzip JSON 对象键';

CREATE INDEX idx_xtjs_tender_reviews_active_update_time
    ON xtjs_tender_reviews (update_time DESC, identifier_id DESC)
    WHERE deleted = FALSE;

CREATE INDEX idx_xtjs_tender_reviews_active_status
    ON xtjs_tender_reviews (status, update_time DESC)
    WHERE deleted = FALSE;
