CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE xtjs_projects
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    identifier_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_name   TEXT      NOT NULL,
    parsing_status INTEGER   NOT NULL DEFAULT 0,
    deleted        BOOLEAN   NOT NULL DEFAULT FALSE,
    create_time    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT
ON TABLE xtjs_projects IS 'XTJS项目表';

COMMENT
ON COLUMN xtjs_projects.identifier_id IS '项目UUID唯一标识符，系统自动生成，作为主键和外键引用目标';
COMMENT
ON COLUMN xtjs_projects.id IS '数据库内部自增数字序号，仅用于内部排序/排查，不作为外键或业务标识';
COMMENT
ON COLUMN xtjs_projects.project_name IS '用户输入的项目名称';
COMMENT
ON COLUMN xtjs_projects.parsing_status IS
    '项目解析状态：0-未开始OCR，1-招标文件OCR完成，2-商务标OCR完成，3-技术标OCR完成';
COMMENT
ON COLUMN xtjs_projects.deleted IS '逻辑删除：false-未删除，true-已删除';
COMMENT
ON COLUMN xtjs_projects.create_time IS '创建时间';
COMMENT
ON COLUMN xtjs_projects.update_time IS '更新时间';

CREATE UNIQUE INDEX uk_xtjs_projects_active_project_name
    ON xtjs_projects (project_name)
    WHERE deleted = FALSE;

CREATE INDEX idx_xtjs_projects_parsing_status
    ON xtjs_projects (parsing_status);

CREATE INDEX idx_xtjs_projects_active_create_time
    ON xtjs_projects (create_time DESC, identifier_id DESC)
    WHERE deleted = FALSE;
